import { mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createHash } from "node:crypto";
import { expect, it } from "vitest";
import { createBackup, stageRestore, restorePending, validateBackup } from "./backups.ts";
it("round trips app records without credentials and checks hashes and paths", () => {
  const root = mkdtempSync(join(tmpdir(), "backups-"));
  writeFileSync(join(root, "bots.json"), '[{"id":"saved"}]');
  writeFileSync(join(root, "config.json"), '{"apiKey":"fixture-private"}');
  writeFileSync(join(root, "webhooks.json"), '{"signingSecret":"fixture-private"}');
  const backup = createBackup(root);
  expect(JSON.stringify(backup)).not.toContain("fixture-private");
  const corrupt = structuredClone(backup); corrupt.files[0]!.text = "[]";
  expect(() => validateBackup(corrupt)).toThrow();
  const escape = structuredClone(backup); escape.files[0]!.path = "../bots.json";
  expect(() => validateBackup(escape)).toThrow();
  const malformed = structuredClone(backup); malformed.files[0]!.text = "[null]"; malformed.files[0]!.sha256 = createHash("sha256").update("[null]").digest("hex");
  expect(() => validateBackup(malformed)).toThrow();
  writeFileSync(join(root, "bots.json"), '[{"id":"current"}]');
  stageRestore(backup, root);
  expect(readFileSync(join(root, "bots.json"), "utf8")).toContain("current");
  expect(restorePending(root)).toBe(true);
  expect(readFileSync(join(root, "bots.json"), "utf8")).toContain("saved");
  expect(restorePending(root)).toBe(false);
});
